/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "DISCORD_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DISCORD_APPLICATION_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "MyVpc": {
      "type": "sst.aws.Vpc"
    }
    "OPENAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SUPABASE_ANON_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SUPABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TELEGRAM_BOT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
